c0 = Course.create(:name => "English C77")
r0 = LsCollegeRequirement.create(:course_id => c0.id, :arts_and_literature => true, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c1 = Course.create(:name => "Environmental Science, Policy, and Management C12")
r1 = LsCollegeRequirement.create(:course_id => c1.id, :arts_and_literature => true, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c2 = Course.create(:name => "Undergraduate and Interdisciplinary Studies C12")
r2 = LsCollegeRequirement.create(:course_id => c2.id, :arts_and_literature => true, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c3 = Course.create(:name => "Environmental Science, Policy, and Management C107")
r3 = LsCollegeRequirement.create(:course_id => c3.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c4 = Course.create(:name => "African American Studies 160")
r4 = LsCollegeRequirement.create(:course_id => c4.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c5 = Course.create(:name => "Arabic 108")
r5 = LsCollegeRequirement.create(:course_id => c5.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c6 = Course.create(:name => "Art, History of 131C")
r6 = LsCollegeRequirement.create(:course_id => c6.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c7 = Course.create(:name => "Art, Practice of 119")
r7 = LsCollegeRequirement.create(:course_id => c7.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c8 = Course.create(:name => "Asian Studies 110")
r8 = LsCollegeRequirement.create(:course_id => c8.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c9 = Course.create(:name => "Buddhist Studies C124")
r9 = LsCollegeRequirement.create(:course_id => c9.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c10 = Course.create(:name => "Celtic Studies 106C")
r10 = LsCollegeRequirement.create(:course_id => c10.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c11 = Course.create(:name => "Celtic Studies 116B")
r11 = LsCollegeRequirement.create(:course_id => c11.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c12 = Course.create(:name => "Celtic Studies 129")
r12 = LsCollegeRequirement.create(:course_id => c12.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c13 = Course.create(:name => "Celtic Studies C168")
r13 = LsCollegeRequirement.create(:course_id => c13.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c14 = Course.create(:name => "Celtic Studies 169")
r14 = LsCollegeRequirement.create(:course_id => c14.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c15 = Course.create(:name => "Chicano Studies 135C")
r15 = LsCollegeRequirement.create(:course_id => c15.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c16 = Course.create(:name => "Chinese 153")
r16 = LsCollegeRequirement.create(:course_id => c16.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c17 = Course.create(:name => "Chinese 183")
r17 = LsCollegeRequirement.create(:course_id => c17.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c18 = Course.create(:name => "Chinese C184")
r18 = LsCollegeRequirement.create(:course_id => c18.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c19 = Course.create(:name => "Chinese 186")
r19 = LsCollegeRequirement.create(:course_id => c19.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c20 = Course.create(:name => "Classics 10A")
r20 = LsCollegeRequirement.create(:course_id => c20.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c21 = Course.create(:name => "Classics 10B")
r21 = LsCollegeRequirement.create(:course_id => c21.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c22 = Course.create(:name => "Classics 28")
r22 = LsCollegeRequirement.create(:course_id => c22.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c23 = Course.create(:name => "Classics 34")
r23 = LsCollegeRequirement.create(:course_id => c23.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c24 = Course.create(:name => "Classics 39A")
r24 = LsCollegeRequirement.create(:course_id => c24.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c25 = Course.create(:name => "Classics 39D")
r25 = LsCollegeRequirement.create(:course_id => c25.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c26 = Course.create(:name => "Classics 100A")
r26 = LsCollegeRequirement.create(:course_id => c26.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c27 = Course.create(:name => "Classics 100B")
r27 = LsCollegeRequirement.create(:course_id => c27.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c28 = Course.create(:name => "Classics 124")
r28 = LsCollegeRequirement.create(:course_id => c28.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c29 = Course.create(:name => "Classics 161")
r29 = LsCollegeRequirement.create(:course_id => c29.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c30 = Course.create(:name => "Classics 178")
r30 = LsCollegeRequirement.create(:course_id => c30.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c31 = Course.create(:name => "Comparative Literature 171")
r31 = LsCollegeRequirement.create(:course_id => c31.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c32 = Course.create(:name => "Comparative Literature 20")
r32 = CampusRequirement.create(:course_id => c32.id, :american_cultures => true)
c33 = Course.create(:name => "Comparative Literature 20")
r33 = LsCollegeRequirement.create(:course_id => c33.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c34 = Course.create(:name => "East Asian Languages 105")
r34 = LsCollegeRequirement.create(:course_id => c34.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c35 = Course.create(:name => "East Asian Languages C124")
r35 = LsCollegeRequirement.create(:course_id => c35.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c36 = Course.create(:name => "German 100")
r36 = LsCollegeRequirement.create(:course_id => c36.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c37 = Course.create(:name => "German 101")
r37 = LsCollegeRequirement.create(:course_id => c37.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c38 = Course.create(:name => "German 102A")
r38 = LsCollegeRequirement.create(:course_id => c38.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c39 = Course.create(:name => "German C113")
r39 = LsCollegeRequirement.create(:course_id => c39.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c40 = Course.create(:name => "German 142")
r40 = LsCollegeRequirement.create(:course_id => c40.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c41 = Course.create(:name => "German 143")
r41 = LsCollegeRequirement.create(:course_id => c41.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c42 = Course.create(:name => "German C159")
r42 = LsCollegeRequirement.create(:course_id => c42.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c43 = Course.create(:name => "German 162")
r43 = LsCollegeRequirement.create(:course_id => c43.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c44 = Course.create(:name => "German 176")
r44 = LsCollegeRequirement.create(:course_id => c44.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c45 = Course.create(:name => "Greek 100")
r45 = LsCollegeRequirement.create(:course_id => c45.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c46 = Course.create(:name => "Greek 105")
r46 = LsCollegeRequirement.create(:course_id => c46.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c47 = Course.create(:name => "Greek 123")
r47 = LsCollegeRequirement.create(:course_id => c47.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c48 = Course.create(:name => "Hindi-Urdu 101A")
r48 = LsCollegeRequirement.create(:course_id => c48.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c49 = Course.create(:name => "Hindi-Urdu 101B")
r49 = LsCollegeRequirement.create(:course_id => c49.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c50 = Course.create(:name => "Italian Studies 30")
r50 = LsCollegeRequirement.create(:course_id => c50.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c51 = Course.create(:name => "Political Science 108A")
r51 = UniversityRequirement.create(:course_id => c51.id, :entry_level_writing => false, :american_history_and_institutions => true)
c52 = Course.create(:name => "History 7A")
r52 = UniversityRequirement.create(:course_id => c52.id, :entry_level_writing => false, :american_history_and_institutions => true)
c53 = Course.create(:name => "History 7A")
r53 = CampusRequirement.create(:course_id => c53.id, :american_cultures => true)
c54 = Course.create(:name => "History 7B")
r54 = UniversityRequirement.create(:course_id => c54.id, :entry_level_writing => false, :american_history_and_institutions => true)
c55 = Course.create(:name => "History 7B")
r55 = CampusRequirement.create(:course_id => c55.id, :american_cultures => true)
c56 = Course.create(:name => "History 130B")
r56 = UniversityRequirement.create(:course_id => c56.id, :entry_level_writing => false, :american_history_and_institutions => true)
c57 = Course.create(:name => "History 131A")
r57 = UniversityRequirement.create(:course_id => c57.id, :entry_level_writing => false, :american_history_and_institutions => true)
c58 = Course.create(:name => "History 131B")
r58 = UniversityRequirement.create(:course_id => c58.id, :entry_level_writing => false, :american_history_and_institutions => true)
c59 = Course.create(:name => "History N131B")
r59 = UniversityRequirement.create(:course_id => c59.id, :entry_level_writing => false, :american_history_and_institutions => true)
c60 = Course.create(:name => "History 138")
r60 = UniversityRequirement.create(:course_id => c60.id, :entry_level_writing => false, :american_history_and_institutions => true)
c61 = Course.create(:name => "Political Science 1")
r61 = UniversityRequirement.create(:course_id => c61.id, :entry_level_writing => false, :american_history_and_institutions => true)
c62 = Course.create(:name => "Political Science 1AC")
r62 = UniversityRequirement.create(:course_id => c62.id, :entry_level_writing => false, :american_history_and_institutions => true)
c63 = Course.create(:name => "CW R1A")
r63 = UniversityRequirement.create(:course_id => c63.id, :entry_level_writing => true, :american_history_and_institutions => false)
c64 = Course.create(:name => "Comparative Literature 21")
r64 = CampusRequirement.create(:course_id => c64.id, :american_cultures => true)
c65 = Course.create(:name => "Comparative Literature 34")
r65 = CampusRequirement.create(:course_id => c65.id, :american_cultures => true)
