# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
 

# colleges
college0 = College.create(:name => "College of Letter & Science")
college1 = College.create(:name => "Haas School of Business")
college2 = College.create(:name => "College of Chemistry")
college3 = College.create(:name => "Graduate School of Education")
college4 = College.create(:name => "College of Engineering")
college5 = College.create(:name => "College of Environmental Design")
college6 = College.create(:name => "School of Information")
college7 = College.create(:name => "Graduate School of Journalism")
college8 = College.create(:name => "School of Law")
college9 = College.create(:name => "College of Natural Resources")
college10 = College.create(:name => "School of Optometry")
college11 = College.create(:name => "School of Public Health")
college12 = College.create(:name => "Richard & Rhoda Goldman School of Public Policy")
college13 = College.create(:name => "School of Social Welfare")

# majors 
major0 = Major.create(:name => "Chemistry", :college_id => college2.id)
major1 = Major.create(:name => "Chemical Biology", :college_id => college2.id)
major2 = Major.create(:name => "EECS", :college_id => college4.id)
major3 = Major.create(:name => "Nuclear Engineering", :college_id => college4.id)
major4 = Major.create(:name => "Chinese", :college_id => college0.id)
major5 = Major.create(:name => "Computer Science", :college_id => college0.id)
major6 = Major.create(:name => "Microbial Biology", :college_id => college9.id)


# # entry_level_writing
# c0 = Course.create(:name => "Entry Level Writing 1A")
# c1 = Course.create(:name => "Entry Level Writing 2A")

# # american_history_and_institutions
# c2 = Course.create(:name => "History 1A")
# c3 = Course.create(:name => "History 2A")

# # american_cultures
# c4 = Course.create(:name => "American Cultures 1A")
# c5 = Course.create(:name => "American Cultures 2A")

# # reading_and_composition
# c6 = Course.create(:name => "Reading and Composition 1A")
# c7 = Course.create(:name => "Reading and Composition 2A")

# # quantitative_reasoning
# c8 = Course.create(:name => "Quantitative Reasoning 1A")
# c9 = Course.create(:name => "Quantitative Reasoning 2A")

# # foreign_language_breadth
# c10 = Course.create(:name => "Foreign Language Breadth 1A")
# c11 = Course.create(:name => "Foreign Language Breadth 2A")

# # arts_and_literature
# c12 = Course.create(:name => "Arts and Literature 1A")
# c13 = Course.create(:name => "Arts and Literature 2A")

# # biological_science
# c14 = Course.create(:name => "Biological Science 1A")
# c15 = Course.create(:name => "Biological Science 2A")

# # historical_studies
# c16 = Course.create(:name => "Historical Studies 1A")
# c17 = Course.create(:name => "Historical Studies 2A")

# # international_studies
# c18 = Course.create(:name => "International Studies 1A")
# c19 = Course.create(:name => "International Studies 2A")

# # philosophy_and_values
# c20 = Course.create(:name => "Philosophy and Values 1A")
# c21 = Course.create(:name => "Philosophy and Values 2A")

# # physical_science
# c22 = Course.create(:name => "Physical Science 1A")
# c23 = Course.create(:name => "Physical Science 2A")

# # social_and_behavioral_sciences
# c24 = Course.create(:name => "Social and Behavioral Sciences 1A")
# c25 = Course.create(:name => "Social and Behavioral Sciences 2A")

# # entry_level_writing
# m0 = UniversityRequirement.create(:course_id => c0.id, :entry_level_writing => true, :american_history_and_institutions => false)
# m1 = UniversityRequirement.create(:course_id => c1.id, :entry_level_writing => true, :american_history_and_institutions => false)

# # american_history_and_institutions
# m2 = UniversityRequirement.create(:course_id => c2.id, :entry_level_writing => false, :american_history_and_institutions => true)
# m3 = UniversityRequirement.create(:course_id => c3.id, :entry_level_writing => false, :american_history_and_institutions => true)

# # american_cultures
# m4 = CampusRequirement.create(:course_id => c4.id, :american_cultures => true)
# m5 = CampusRequirement.create(:course_id => c5.id, :american_cultures => true)

# # reading_and_composition
# m6 = LsCollegeRequirement.create(:course_id => c6.id, :reading_and_composition => true)
# m7 = LsCollegeRequirement.create(:course_id => c7.id, :reading_and_composition => true)

# # quantitative_reasoning
# m8 = LsCollegeRequirement.create(:course_id => c8.id, :quantitative_reasoning => true) 
# m9 = LsCollegeRequirement.create(:course_id => c9.id, :quantitative_reasoning => true)

# # foreign_language_breadth
# m10 = LsCollegeRequirement.create(:course_id => c10.id, :foreign_language_breadth => true)
# m11 = LsCollegeRequirement.create(:course_id => c11.id, :foreign_language_breadth => true)

# # arts_and_literature
# m12 = LsCollegeRequirement.create(:course_id => c12.id, :arts_and_literature => true)
# m13 = LsCollegeRequirement.create(:course_id => c13.id, :arts_and_literature => true)

# # biological_science
# m14 = LsCollegeRequirement.create(:course_id => c14.id, :biological_science => true)
# m15 = LsCollegeRequirement.create(:course_id => c15.id, :biological_science => true)

# # historical_studies
# m16 = LsCollegeRequirement.create(:course_id => c16.id, :historical_studies => true)
# m17 = LsCollegeRequirement.create(:course_id => c17.id, :historical_studies => true)

# # international_studies
# m18 = LsCollegeRequirement.create(:course_id => c18.id, :international_studies => true)
# m19 = LsCollegeRequirement.create(:course_id => c19.id, :international_studies => true)

# # philosophy_and_values
# m20 = LsCollegeRequirement.create(:course_id => c20.id, :philosophy_and_values => true)
# m21 = LsCollegeRequirement.create(:course_id => c21.id, :philosophy_and_values => true)

# # physical_science
# m22 = LsCollegeRequirement.create(:course_id => c22.id, :physical_science => true)
# m23 = LsCollegeRequirement.create(:course_id => c23.id, :physical_science => true)

# # social_and_behavioral_sciences
# m24 = LsCollegeRequirement.create(:course_id => c24.id, :social_and_behavioral_sciences => true)
# m25 = LsCollegeRequirement.create(:course_id => c25.id, :social_and_behavioral_sciences => true)


# major requriements, so far we only have requirements for LS CS
c926 = Course.create(:name => "CS 61A")
c927 = Course.create(:name => "CS 61B")
c928 = Course.create(:name => "CS 61C")
c929 = Course.create(:name => "Math 1A")
c930 = Course.create(:name => "Math 1B")
c931 = Course.create(:name => "Math 54")
c932 = Course.create(:name => "CS 70")
c933 = Course.create(:name => "EE 20")
c934 = Course.create(:name => "EE 40")
c935 = Course.create(:name => "EE 42")
c936 = Course.create(:name => "CS 170")
c937 = Course.create(:name => "CS 162")
c938 = Course.create(:name => "CS 150")
c939 = Course.create(:name => "CS 152")
c940 = Course.create(:name => "CS 160")
c941 = Course.create(:name => "CS 161")
c942 = Course.create(:name => "CS 164")
c943 = Course.create(:name => "CS 169")
c944 = Course.create(:name => "CS 184")
c945 = Course.create(:name => "CS 186")
c946 = Course.create(:name => "CS 188")



c0 = Course.create(:name => "English C77")
r0 = LsCollegeRequirement.create(:course_id => c0.id, :arts_and_literature => true, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c1 = Course.create(:name => "Environmental Science, Policy, and Management C12")
r1 = LsCollegeRequirement.create(:course_id => c1.id, :arts_and_literature => true, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c2 = Course.create(:name => "Undergraduate and Interdisciplinary Studies C12")
r2 = LsCollegeRequirement.create(:course_id => c2.id, :arts_and_literature => true, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c3 = Course.create(:name => "Environmental Science, Policy, and Management C107")
r3 = LsCollegeRequirement.create(:course_id => c3.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c4 = Course.create(:name => "African American Studies 160")
r4 = LsCollegeRequirement.create(:course_id => c4.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c5 = Course.create(:name => "Arabic 108")
r5 = LsCollegeRequirement.create(:course_id => c5.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c6 = Course.create(:name => "Art, History of 131C")
r6 = LsCollegeRequirement.create(:course_id => c6.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c7 = Course.create(:name => "Art, Practice of 119")
r7 = LsCollegeRequirement.create(:course_id => c7.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c8 = Course.create(:name => "Asian Studies 110")
r8 = LsCollegeRequirement.create(:course_id => c8.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c9 = Course.create(:name => "Buddhist Studies C124")
r9 = LsCollegeRequirement.create(:course_id => c9.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c10 = Course.create(:name => "Celtic Studies 106C")
r10 = LsCollegeRequirement.create(:course_id => c10.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c11 = Course.create(:name => "Celtic Studies 116B")
r11 = LsCollegeRequirement.create(:course_id => c11.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c12 = Course.create(:name => "Celtic Studies 129")
r12 = LsCollegeRequirement.create(:course_id => c12.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c13 = Course.create(:name => "Celtic Studies C168")
r13 = LsCollegeRequirement.create(:course_id => c13.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c14 = Course.create(:name => "Celtic Studies 169")
r14 = LsCollegeRequirement.create(:course_id => c14.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c15 = Course.create(:name => "Chicano Studies 135C")
r15 = LsCollegeRequirement.create(:course_id => c15.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c16 = Course.create(:name => "Chinese 153")
r16 = LsCollegeRequirement.create(:course_id => c16.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c17 = Course.create(:name => "Chinese 183")
r17 = LsCollegeRequirement.create(:course_id => c17.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c18 = Course.create(:name => "Chinese C184")
r18 = LsCollegeRequirement.create(:course_id => c18.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c19 = Course.create(:name => "Chinese 186")
r19 = LsCollegeRequirement.create(:course_id => c19.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c20 = Course.create(:name => "Classics 10A")
r20 = LsCollegeRequirement.create(:course_id => c20.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c21 = Course.create(:name => "Classics 10B")
r21 = LsCollegeRequirement.create(:course_id => c21.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c22 = Course.create(:name => "Classics 28")
r22 = LsCollegeRequirement.create(:course_id => c22.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c23 = Course.create(:name => "Classics 34")
r23 = LsCollegeRequirement.create(:course_id => c23.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c24 = Course.create(:name => "Classics 39A")
r24 = LsCollegeRequirement.create(:course_id => c24.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c25 = Course.create(:name => "Classics 39D")
r25 = LsCollegeRequirement.create(:course_id => c25.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c26 = Course.create(:name => "Classics 100A")
r26 = LsCollegeRequirement.create(:course_id => c26.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c27 = Course.create(:name => "Classics 100B")
r27 = LsCollegeRequirement.create(:course_id => c27.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c28 = Course.create(:name => "Classics 124")
r28 = LsCollegeRequirement.create(:course_id => c28.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c29 = Course.create(:name => "Classics 161")
r29 = LsCollegeRequirement.create(:course_id => c29.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c30 = Course.create(:name => "Classics 178")
r30 = LsCollegeRequirement.create(:course_id => c30.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c31 = Course.create(:name => "Comparative Literature 171")
r31 = LsCollegeRequirement.create(:course_id => c31.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c32 = Course.create(:name => "Comparative Literature 20")
r32 = CampusRequirement.create(:course_id => c32.id, :american_cultures => true)
c33 = Course.create(:name => "Comparative Literature 20")
r33 = LsCollegeRequirement.create(:course_id => c33.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c34 = Course.create(:name => "East Asian Languages 105")
r34 = LsCollegeRequirement.create(:course_id => c34.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c35 = Course.create(:name => "East Asian Languages C124")
r35 = LsCollegeRequirement.create(:course_id => c35.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c36 = Course.create(:name => "German 100")
r36 = LsCollegeRequirement.create(:course_id => c36.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c37 = Course.create(:name => "German 101")
r37 = LsCollegeRequirement.create(:course_id => c37.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c38 = Course.create(:name => "German 102A")
r38 = LsCollegeRequirement.create(:course_id => c38.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c39 = Course.create(:name => "German C113")
r39 = LsCollegeRequirement.create(:course_id => c39.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c40 = Course.create(:name => "German 142")
r40 = LsCollegeRequirement.create(:course_id => c40.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c41 = Course.create(:name => "German 143")
r41 = LsCollegeRequirement.create(:course_id => c41.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c42 = Course.create(:name => "German C159")
r42 = LsCollegeRequirement.create(:course_id => c42.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c43 = Course.create(:name => "German 162")
r43 = LsCollegeRequirement.create(:course_id => c43.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c44 = Course.create(:name => "German 176")
r44 = LsCollegeRequirement.create(:course_id => c44.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c45 = Course.create(:name => "Greek 100")
r45 = LsCollegeRequirement.create(:course_id => c45.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c46 = Course.create(:name => "Greek 105")
r46 = LsCollegeRequirement.create(:course_id => c46.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c47 = Course.create(:name => "Greek 123")
r47 = LsCollegeRequirement.create(:course_id => c47.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c48 = Course.create(:name => "Hindi-Urdu 101A")
r48 = LsCollegeRequirement.create(:course_id => c48.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c49 = Course.create(:name => "Hindi-Urdu 101B")
r49 = LsCollegeRequirement.create(:course_id => c49.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c50 = Course.create(:name => "Italian Studies 30")
r50 = LsCollegeRequirement.create(:course_id => c50.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c51 = Course.create(:name => "Italian Studies 130A")
r51 = LsCollegeRequirement.create(:course_id => c51.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c52 = Course.create(:name => "Italian Studies 130B")
r52 = LsCollegeRequirement.create(:course_id => c52.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c53 = Course.create(:name => "Jewish Studies 39D")
r53 = LsCollegeRequirement.create(:course_id => c53.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c54 = Course.create(:name => "Khmer 101A")
r54 = LsCollegeRequirement.create(:course_id => c54.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c55 = Course.create(:name => "Khmer 101B")
r55 = LsCollegeRequirement.create(:course_id => c55.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c56 = Course.create(:name => "Latin 116")
r56 = LsCollegeRequirement.create(:course_id => c56.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c57 = Course.create(:name => "Legal Studies 114")
r57 = LsCollegeRequirement.create(:course_id => c57.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c58 = Course.create(:name => "Letters and Science 27")
r58 = LsCollegeRequirement.create(:course_id => c58.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c59 = Course.create(:name => "Letters and Science 116")
r59 = LsCollegeRequirement.create(:course_id => c59.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c60 = Course.create(:name => "Letters and Science 123")
r60 = LsCollegeRequirement.create(:course_id => c60.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c61 = Course.create(:name => "Linguistics 106")
r61 = LsCollegeRequirement.create(:course_id => c61.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c62 = Course.create(:name => "Music 132")
r62 = LsCollegeRequirement.create(:course_id => c62.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c63 = Course.create(:name => "Music 136")
r63 = LsCollegeRequirement.create(:course_id => c63.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c64 = Course.create(:name => "Music 139")
r64 = LsCollegeRequirement.create(:course_id => c64.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c65 = Course.create(:name => "Music C134C")
r65 = LsCollegeRequirement.create(:course_id => c65.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c66 = Course.create(:name => "Music 133D")
r66 = LsCollegeRequirement.create(:course_id => c66.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c67 = Course.create(:name => "Music 133C")
r67 = LsCollegeRequirement.create(:course_id => c67.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c68 = Course.create(:name => "Music 135A")
r68 = LsCollegeRequirement.create(:course_id => c68.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c69 = Course.create(:name => "Music 134A")
r69 = LsCollegeRequirement.create(:course_id => c69.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c70 = Course.create(:name => "Music 134B")
r70 = LsCollegeRequirement.create(:course_id => c70.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c71 = Course.create(:name => "Music 74")
r71 = LsCollegeRequirement.create(:course_id => c71.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c72 = Course.create(:name => "Native American Studies 150")
r72 = LsCollegeRequirement.create(:course_id => c72.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c73 = Course.create(:name => "Near Eastern Studies 34")
r73 = LsCollegeRequirement.create(:course_id => c73.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c74 = Course.create(:name => "Near Eastern Studies C92")
r74 = LsCollegeRequirement.create(:course_id => c74.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c75 = Course.create(:name => "Near Eastern Studies 102A")
r75 = LsCollegeRequirement.create(:course_id => c75.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c76 = Course.create(:name => "Near Eastern Studies 102B")
r76 = LsCollegeRequirement.create(:course_id => c76.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c77 = Course.create(:name => "Near Eastern Studies 105A")
r77 = LsCollegeRequirement.create(:course_id => c77.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c78 = Course.create(:name => "Near Eastern Studies 105B")
r78 = LsCollegeRequirement.create(:course_id => c78.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c79 = Course.create(:name => "Near Eastern Studies 127")
r79 = LsCollegeRequirement.create(:course_id => c79.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c80 = Course.create(:name => "Near Eastern Studies 154")
r80 = LsCollegeRequirement.create(:course_id => c80.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c81 = Course.create(:name => "Near Eastern Studies 165")
r81 = LsCollegeRequirement.create(:course_id => c81.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c82 = Course.create(:name => "Religious Studies C108")
r82 = LsCollegeRequirement.create(:course_id => c82.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c83 = Course.create(:name => "Religious Studies C109")
r83 = LsCollegeRequirement.create(:course_id => c83.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c84 = Course.create(:name => "Religious Studies 115")
r84 = LsCollegeRequirement.create(:course_id => c84.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c85 = Course.create(:name => "Religious Studies C118")
r85 = LsCollegeRequirement.create(:course_id => c85.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c86 = Course.create(:name => "Religious Studies C163")
r86 = LsCollegeRequirement.create(:course_id => c86.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c87 = Course.create(:name => "Religious Studies C165")
r87 = LsCollegeRequirement.create(:course_id => c87.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c88 = Course.create(:name => "Religious Studies C166")
r88 = LsCollegeRequirement.create(:course_id => c88.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c89 = Course.create(:name => "Religious Studies 171AC")
r89 = LsCollegeRequirement.create(:course_id => c89.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c90 = Course.create(:name => "Rhetoric 50A")
r90 = LsCollegeRequirement.create(:course_id => c90.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c91 = Course.create(:name => "Rhetoric 50B")
r91 = LsCollegeRequirement.create(:course_id => c91.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c92 = Course.create(:name => "Rhetoric 50C")
r92 = LsCollegeRequirement.create(:course_id => c92.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c93 = Course.create(:name => "Rhetoric 50D")
r93 = LsCollegeRequirement.create(:course_id => c93.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c94 = Course.create(:name => "Rhetoric 103A")
r94 = LsCollegeRequirement.create(:course_id => c94.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c95 = Course.create(:name => "Rhetoric 103B")
r95 = LsCollegeRequirement.create(:course_id => c95.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c96 = Course.create(:name => "Rhetoric 141AC")
r96 = LsCollegeRequirement.create(:course_id => c96.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c97 = Course.create(:name => "Scandinavian 100A")
r97 = LsCollegeRequirement.create(:course_id => c97.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c98 = Course.create(:name => "Scandinavian 100B")
r98 = LsCollegeRequirement.create(:course_id => c98.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c99 = Course.create(:name => "Scandinavian C160")
r99 = LsCollegeRequirement.create(:course_id => c99.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c100 = Course.create(:name => "Scandinavian 170")
r100 = LsCollegeRequirement.create(:course_id => c100.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c101 = Course.create(:name => "Slavic R37W")
r101 = LsCollegeRequirement.create(:course_id => c101.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c102 = Course.create(:name => "Slavic 39C")
r102 = LsCollegeRequirement.create(:course_id => c102.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c103 = Course.create(:name => "Slavic 50")
r103 = LsCollegeRequirement.create(:course_id => c103.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c104 = Course.create(:name => "Slavic 134C")
r104 = LsCollegeRequirement.create(:course_id => c104.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c105 = Course.create(:name => "Slavic 134D")
r105 = LsCollegeRequirement.create(:course_id => c105.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c106 = Course.create(:name => "Slavic 134G")
r106 = LsCollegeRequirement.create(:course_id => c106.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c107 = Course.create(:name => "South and Southeast Asian Studies C113")
r107 = LsCollegeRequirement.create(:course_id => c107.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c108 = Course.create(:name => "South Asian C128")
r108 = LsCollegeRequirement.create(:course_id => c108.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c109 = Course.create(:name => "South Asian 129")
r109 = LsCollegeRequirement.create(:course_id => c109.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c110 = Course.create(:name => "South Asian 131")
r110 = LsCollegeRequirement.create(:course_id => c110.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c111 = Course.create(:name => "South Asian C140")
r111 = LsCollegeRequirement.create(:course_id => c111.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c112 = Course.create(:name => "South Asian C142")
r112 = LsCollegeRequirement.create(:course_id => c112.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c113 = Course.create(:name => "South Asian 165")
r113 = LsCollegeRequirement.create(:course_id => c113.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c114 = Course.create(:name => "Spanish 129")
r114 = LsCollegeRequirement.create(:course_id => c114.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c115 = Course.create(:name => "Vietnamese 101B")
r115 = LsCollegeRequirement.create(:course_id => c115.id, :arts_and_literature => true, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c116 = Course.create(:name => "Biochemistry 170B")
r116 = LsCollegeRequirement.create(:course_id => c116.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c117 = Course.create(:name => "Chemical Engineering 170A")
r117 = LsCollegeRequirement.create(:course_id => c117.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c118 = Course.create(:name => "Chemical Engineering 170E")
r118 = LsCollegeRequirement.create(:course_id => c118.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c119 = Course.create(:name => "Civil and Environmental Engineering 113")
r119 = LsCollegeRequirement.create(:course_id => c119.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c120 = Course.create(:name => "Earth and Planetary Science C82")
r120 = LsCollegeRequirement.create(:course_id => c120.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c121 = Course.create(:name => "Earth and Planetary Science C129")
r121 = LsCollegeRequirement.create(:course_id => c121.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c122 = Course.create(:name => "Earth and Planetary Science 185")
r122 = LsCollegeRequirement.create(:course_id => c122.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c123 = Course.create(:name => "Environmental Science, Policy, and Management 2")
r123 = LsCollegeRequirement.create(:course_id => c123.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c124 = Course.create(:name => "Environmental Science, Policy, and Management 15")
r124 = LsCollegeRequirement.create(:course_id => c124.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c125 = Course.create(:name => "Environmental Science, Policy, and Management 129")
r125 = LsCollegeRequirement.create(:course_id => c125.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c126 = Course.create(:name => "Environmental Science, Policy, and Management C129")
r126 = LsCollegeRequirement.create(:course_id => c126.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c127 = Course.create(:name => "Environmental Science, Policy, and Management 181")
r127 = LsCollegeRequirement.create(:course_id => c127.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c128 = Course.create(:name => "Environmental Sciences 10")
r128 = LsCollegeRequirement.create(:course_id => c128.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c129 = Course.create(:name => "Environmental Sciences 125")
r129 = LsCollegeRequirement.create(:course_id => c129.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c130 = Course.create(:name => "Geography 30")
r130 = LsCollegeRequirement.create(:course_id => c130.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c131 = Course.create(:name => "Geography 40")
r131 = LsCollegeRequirement.create(:course_id => c131.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c132 = Course.create(:name => "Geography C82")
r132 = LsCollegeRequirement.create(:course_id => c132.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c133 = Course.create(:name => "Geography 143")
r133 = LsCollegeRequirement.create(:course_id => c133.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c134 = Course.create(:name => "Letters and Science 18")
r134 = LsCollegeRequirement.create(:course_id => c134.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c135 = Course.create(:name => "Letters and Science 117")
r135 = LsCollegeRequirement.create(:course_id => c135.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c136 = Course.create(:name => "Letters and Science 126")
r136 = LsCollegeRequirement.create(:course_id => c136.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c137 = Course.create(:name => "Physics 177")
r137 = LsCollegeRequirement.create(:course_id => c137.id, :arts_and_literature => false, :biological_science => true, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c138 = Course.create(:name => "Buddhist Studies C128")
r138 = LsCollegeRequirement.create(:course_id => c138.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c139 = Course.create(:name => "Buddhist Studies 181")
r139 = LsCollegeRequirement.create(:course_id => c139.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c140 = Course.create(:name => "East Asian Languages C128")
r140 = LsCollegeRequirement.create(:course_id => c140.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c141 = Course.create(:name => "Global Poverty and Practice 105")
r141 = LsCollegeRequirement.create(:course_id => c141.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c142 = Course.create(:name => "Integrative Biology C158")
r142 = LsCollegeRequirement.create(:course_id => c142.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => false, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c143 = Course.create(:name => "Interdisciplinary Studies 60")
r143 = LsCollegeRequirement.create(:course_id => c143.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c144 = Course.create(:name => "Interdisciplinary Studies 100A")
r144 = LsCollegeRequirement.create(:course_id => c144.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c145 = Course.create(:name => "Interdisciplinary Studies 100E")
r145 = LsCollegeRequirement.create(:course_id => c145.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c146 = Course.create(:name => "International and Area Studies 105")
r146 = LsCollegeRequirement.create(:course_id => c146.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c147 = Course.create(:name => "International and Area Studies 105A")
r147 = LsCollegeRequirement.create(:course_id => c147.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c148 = Course.create(:name => "International and Area Studies 105B")
r148 = LsCollegeRequirement.create(:course_id => c148.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c149 = Course.create(:name => "Legal Studies 161")
r149 = LsCollegeRequirement.create(:course_id => c149.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c150 = Course.create(:name => "Peace and Conflict Studies 126")
r150 = LsCollegeRequirement.create(:course_id => c150.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c151 = Course.create(:name => "Peace and Conflict Studies 127")
r151 = LsCollegeRequirement.create(:course_id => c151.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c152 = Course.create(:name => "Peace and Conflict Studies 127A")
r152 = LsCollegeRequirement.create(:course_id => c152.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c153 = Course.create(:name => "Peace and Conflict Studies 127B")
r153 = LsCollegeRequirement.create(:course_id => c153.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c154 = Course.create(:name => "Peace and Conflict Studies N127A")
r154 = LsCollegeRequirement.create(:course_id => c154.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c155 = Course.create(:name => "Peace and Conflict Studies 128AC")
r155 = LsCollegeRequirement.create(:course_id => c155.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c156 = Course.create(:name => "Peace and Conflict Studies 151")
r156 = LsCollegeRequirement.create(:course_id => c156.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c157 = Course.create(:name => "Peace and Conflict Studies 164A")
r157 = LsCollegeRequirement.create(:course_id => c157.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c158 = Course.create(:name => "Peace and Conflict Studies 164B")
r158 = LsCollegeRequirement.create(:course_id => c158.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c159 = Course.create(:name => "Political Economy 101")
r159 = LsCollegeRequirement.create(:course_id => c159.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c160 = Course.create(:name => "Political Science 117")
r160 = LsCollegeRequirement.create(:course_id => c160.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c161 = Course.create(:name => "Political Science 124C")
r161 = LsCollegeRequirement.create(:course_id => c161.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c162 = Course.create(:name => "Rhetoric 39G")
r162 = LsCollegeRequirement.create(:course_id => c162.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c163 = Course.create(:name => "South and Southeast Asian Studies C145")
r163 = LsCollegeRequirement.create(:course_id => c163.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c164 = Course.create(:name => "Southeast Asian C145")
r164 = LsCollegeRequirement.create(:course_id => c164.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => true, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c165 = Course.create(:name => "Optometry 39A")
r165 = LsCollegeRequirement.create(:course_id => c165.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => true, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c166 = Course.create(:name => "Political Science 108A")
r166 = UniversityRequirement.create(:course_id => c166.id, :entry_level_writing => false, :american_history_and_institutions => true)
c167 = Course.create(:name => "Political Science 108A")
r167 = LsCollegeRequirement.create(:course_id => c167.id, :arts_and_literature => false, :biological_science => false, :foreign_language_breadth => false, :historical_studies => false, :international_studies => false, :philosophy_and_values => true, :physical_science => false, :quantitative_reasoning => false, :reading_and_composition => false, :social_and_behavioral_sciences => false)
c168 = Course.create(:name => "History 7A")
r168 = UniversityRequirement.create(:course_id => c168.id, :entry_level_writing => false, :american_history_and_institutions => true)
c169 = Course.create(:name => "History 7A")
r169 = CampusRequirement.create(:course_id => c169.id, :american_cultures => true)
c170 = Course.create(:name => "History 7B")
r170 = UniversityRequirement.create(:course_id => c170.id, :entry_level_writing => false, :american_history_and_institutions => true)
c171 = Course.create(:name => "History 7B")
r171 = CampusRequirement.create(:course_id => c171.id, :american_cultures => true)
c406 = Course.create(:name => "History 130B")
r406 = UniversityRequirement.create(:course_id => c406.id, :entry_level_writing => false, :american_history_and_institutions => true)
c407 = Course.create(:name => "History 131A")
r407 = UniversityRequirement.create(:course_id => c407.id, :entry_level_writing => false, :american_history_and_institutions => true)
c408 = Course.create(:name => "History 131B")
r408 = UniversityRequirement.create(:course_id => c408.id, :entry_level_writing => false, :american_history_and_institutions => true)
c409 = Course.create(:name => "History N131B")
r409 = UniversityRequirement.create(:course_id => c409.id, :entry_level_writing => false, :american_history_and_institutions => true)
c410 = Course.create(:name => "History 138")
r410 = UniversityRequirement.create(:course_id => c410.id, :entry_level_writing => false, :american_history_and_institutions => true)
c411 = Course.create(:name => "Political Science 1")
r411 = UniversityRequirement.create(:course_id => c411.id, :entry_level_writing => false, :american_history_and_institutions => true)
c412 = Course.create(:name => "Political Science 1AC")
r412 = UniversityRequirement.create(:course_id => c412.id, :entry_level_writing => false, :american_history_and_institutions => true)
c413 = Course.create(:name => "CW R1A")
r413 = UniversityRequirement.create(:course_id => c413.id, :entry_level_writing => true, :american_history_and_institutions => false)
c414 = Course.create(:name => "Comparative Literature 21")
r414 = CampusRequirement.create(:course_id => c414.id, :american_cultures => true)
c415 = Course.create(:name => "Comparative Literature 34")
r415 = CampusRequirement.create(:course_id => c415.id, :american_cultures => true)

